name: Arduino CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compile:
    name: Compile sketches (Arduino Uno)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            - firmware/fire_fighting_robot
            - firmware/manual_joystick_control
          enable-deltas-report: false
